# Generated by hand for TanPit B03：放液三勾

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pit",
            name="cover_closed",
            field=models.BooleanField(default=False, verbose_name="渠盖已盖"),
        ),
        migrations.AddField(
            model_name="pit",
            name="scraper_stowed",
            field=models.BooleanField(default=False, verbose_name="刮板已收"),
        ),
        migrations.AddField(
            model_name="pit",
            name="rail_reset",
            field=models.BooleanField(default=False, verbose_name="护栏已复位"),
        ),
    ]
