# Generated by hand for TanPit 三勾清单

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pits", "0001_initial"),
    ]
    operations = [
        migrations.CreateModel(
            name="DrainChecklist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("cover_closed", models.BooleanField(default=False)),
                ("scraper_stowed", models.BooleanField(default=False)),
                ("guard_restored", models.BooleanField(default=False)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="pits.pit",
                    ),
                ),
            ],
        ),
    ]
